lenguage: node_js

cache:
  directories: 
    - node_modules
    - ~/.npm

node_js:
  - '15'


git: 
  depth: 3


branches:
  only: 
  - main

addons:
  sonarcloud: 
    organization: 'william10101995'
    token:
      secure: "a4jjg/ifeC1H5R4wKfZZWhfSv9ImeqHI4sI9tZ+5WmpnHSK8xz9SD/Xz3AFaVvvcvw20L/wBSlc7ZznAY788Eh0qKxv+g3/GCvRFaYpmIc6l0sR/Y1hkKG873QdZCn40bSB/rIe3Yh7S1/ZbMzqM7sB6AjY11GPBImdDniRK1j8L0CJ/NuY92cSjqg3nr5NKN36Buwj7moOLZE6do6uvZnhOE46+ueTs1mdrUFhqOpU//qZnHXFYYzwM3wzz9z5rZ43cGtani24B7tKN1ts8RwmrxPM89UO5h1UOdz1JkdTuWpecR/wqYQQwMBXk7Hkp4gjoBsnLvkRIaoXOtCamPC2Cq2dABdvDgc5Lke+hQgfVD67Sug/AlfcfVZozB8srS31CfRjsqpID7vMHewmLCFnYWWmie2bgPPnL+yxjWlPf5kKeA7+7ZuC9Ih9S9r0yNS6UhwRLLMDpvHiP11ZiSJHjMHabVtTU4STZR6yiVrYtSEO11e+Nd5bIARXI5NYK2WME143Y+AyQcNtTpTLH4LgTgvPN9Nwtrw7dX043RSd20u2wy587EIk6oWnMIaCQrnmwjfIsZempvESsP1F3p2MuKYvsIWmAu5WkYP4iG4sQ4fXSNDQspqjb7SCqgNurtp2cPXqSFd7oM6DtvI6nLU2PBsykRqdTKUECpGoHPkM="

script:
  - npm run coverage
  - sonar-scanner 

notifications:
  slack:
    secure: "zSn5HjaCHUk2O7pCJ8qWNykIzc/jsUEkOWYPoGIbFVdfYZV2GcsM5HqPdUM+9vYup0L+cd6SMg6yIt6AVWXOc6Twzsvi7Jgn9EtzFa84IKihoYt0M1GQKyZV4DDZa1x7ahWxkSLxS3UXY85tvSM7PhiIiRmNKkOS/gMuiTQ/IfN2Vv+IfIY5Ajz5ReYZfa83nPJ1vyx0q1w1N9jUWVNzop9bvX0Azr/AdLHmHM8kU5kO60vT6gcjhd2VhnXfppSJOg1qpovOdFTt5nhSFEfQ5AgVYdKQbQxZMHAJk4L+6T1N9B0793QtXq//PKJDncP6l8MGQVUp/+CwW2R5joOs3ZefSzAiW4OVvcjZVEqfmJ805qczUNt/osu8nx1hfEuHSUp4DXi9unSZPOemuO49L7kEUU6DXkTPHtrPR97EpnePUYUoRzTYXLb0NKon7VruJJqw3w+fm0aZY6xj73l/sW5iW0VaaWl8n4+zh40Y/bX+64CTx00Z+H8gGX2JmIzrT3hmuLH3SjdgZaW5Cpde49ZqsBykDKjvyuNQiNRyRY5oVRpaY6iK6t+IHz5fUupai3sOpk37aFcqrcv4xc9x2tZcsQI4iMy8hkE67ngoedynBCxnze57d9Pm+aItVI4P3r3TzEBNvDb118C6BwBylj84ri7IDxGODXEpMDRYG9U="

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: "lOkjs2y8DNMR4giMZBa9gVekHu0J/5qEUsTh1bPCFmENyueDxXa1VjBuZUXgPuK6n+SPwzjBsIkFrqu8qVLW8f3yRkJ+wvj4kOVZSRdY+yaQ3dW6W8Oki4GkorG0S0he+KndVDJz0rz7ceMKxcXxdxq48oNP01qTiMzU21rgFDBKKC0kv+xTyvVNkywOA+X+GPLy3jLihZN+qcdqJngRGBeA8CRY8xPZcREORZf3ocO7KlkuR27G248yo7B83o/qLZTPlB8xri5z9zPBKqp+6d2w0Oo+31mxRX/4U+PY4xXPvj/48p/lnkZ5TY+cGTQ3jBVYrykxpokWdWWTGveusY3KaAzCGVTyNpqlGzLI+yJKjXFpgSezlIU1LXYJtmN0S3VmuRjDdT47j0CwklebJQjlHunInDSReD2XqfMTDW4RnvmOC5lMpbwd+B6viSLNQBwq4kZjZn5nAqR9aVbS1lnOz6cbzW2ihGIMUV9o+b1qcLpkS9B/yT39aem3URVzgQyYxmifx9z8NDIlc1o3pQ23Zfgz1Y2PJexj2f71+NBEQODMO4wPqkX4lulYeXtsLRW3GazcUfmoytb5A0ipHIwrhCFI0xIRFMEiGNbDOtk8Qsjq0QRh5SSR/3eAkjjsWFIxboRaDDbKH6ExLifoS4GYf5a0spGyPWWMenqJTSE="
  app: cicdwilliamlopez
  on: 
    repo: William10101995/CI-CD
    branch: main
