lenguage: node_js

cache:
  directories: 
    - node_modules
    - ~/.npm

node_js:
  - '15'

git: 
  depth: 3

branches:
  only: 
  - main

addons:
  sonarcloud: 
    organization: william10101995
    token: 9857e7dba21a2802dff4890b412518092f4c0bca

script:
  - npm run test
  - sonar-scanner -X

notifications:
  slack:
    secure: "zSn5HjaCHUk2O7pCJ8qWNykIzc/jsUEkOWYPoGIbFVdfYZV2GcsM5HqPdUM+9vYup0L+cd6SMg6yIt6AVWXOc6Twzsvi7Jgn9EtzFa84IKihoYt0M1GQKyZV4DDZa1x7ahWxkSLxS3UXY85tvSM7PhiIiRmNKkOS/gMuiTQ/IfN2Vv+IfIY5Ajz5ReYZfa83nPJ1vyx0q1w1N9jUWVNzop9bvX0Azr/AdLHmHM8kU5kO60vT6gcjhd2VhnXfppSJOg1qpovOdFTt5nhSFEfQ5AgVYdKQbQxZMHAJk4L+6T1N9B0793QtXq//PKJDncP6l8MGQVUp/+CwW2R5joOs3ZefSzAiW4OVvcjZVEqfmJ805qczUNt/osu8nx1hfEuHSUp4DXi9unSZPOemuO49L7kEUU6DXkTPHtrPR97EpnePUYUoRzTYXLb0NKon7VruJJqw3w+fm0aZY6xj73l/sW5iW0VaaWl8n4+zh40Y/bX+64CTx00Z+H8gGX2JmIzrT3hmuLH3SjdgZaW5Cpde49ZqsBykDKjvyuNQiNRyRY5oVRpaY6iK6t+IHz5fUupai3sOpk37aFcqrcv4xc9x2tZcsQI4iMy8hkE67ngoedynBCxnze57d9Pm+aItVI4P3r3TzEBNvDb118C6BwBylj84ri7IDxGODXEpMDRYG9U="

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: "o1LmRw+iJseZhDXFETRE3aTTTJ1Bi/7mNoFj7dDB98nEMCtsgseH8fC3Uy6mqU07cf339IlPp1bcQDFp31YKvbHDQkBw4+8wRl9vxGqOhtbwoBUOH1XZFghlxP7Z/yyQBrcthmukyCSBy9bbhtVerCMEslk6WDX0uFxE3msCNB58rMB9zLKJWW1Vdqxqc9IYkBGNyB9KoAY6wDdVG4rW71mXyTrAyPmiRuf7ojQZ3f4Xb/iAmhiuId/bsK13vcgib59vaWxdUCIkcRv1IKMoHrnut4zyJQ8I7oDQlHpSr0B8wEA5kJY0c2h7IpzuPu1E8DCulmITYechcXRUDNlxQrY/55khmzUmCqPh+lCTWs9HmjpHF/jZ2oFHBEMsSDsRiKOvJBYEkf8fxbaBaRDWvPT9iupTes9efkMC5Eb0CaXF2uRk1g9WDEeGJuEF38LTJ/25xpM8IjNY4LbFpycfrmYCSQCxztniRhYGWg1wDJ54mHc26ezeprS0XAh9MxARaPBTqzV/BUBdQP9SVzeGAtFWh4aLmmkMQB1bPzxTyV/trBeMVB+EhYT5N+PKKD5PuGNHQRsGktbmrrgJO5Wnl7pZ+g6E2L4VdZ+QN2q5sVsaYLbGjPhbadFUKcFBLVOfWSP51ncXEFczEs4m0hBhOFFTzvFSgiKTDBQyeW+KT4Q="
  app: ingenieriadesofware
  on: 
    repo: William10101995/CI-CD
    branch: main
